# Generated by Django 5.0.2 on 2024-02-23 11:34

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('full_content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('tags', models.ManyToManyField(related_name='tech_sharing', to='web_app.tag')),
            ],
        ),
    ]
