# Generated by Django 5.0.2 on 2024-02-23 17:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsharing',
            name='full_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Tech Sharing content'),
        ),
    ]
