# Generated by Django 5.0.2 on 2024-02-27 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_techsharing_full_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsharing',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_sharings', to='web_app.techtopic'),
        ),
    ]
