# Generated by Django 5.0.2 on 2024-02-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_homepagetext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(choices=[('contacts_facebook', 'Facebook'), ('contacts_instagram', 'Instagram'), ('contacts_linkedln', 'Linkedln')], max_length=100, unique=True)),
                ('link', models.TextField()),
            ],
        ),
    ]
