# Generated by Django 5.0.2 on 2024-03-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_skillsection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillSection',
            new_name='Skills',
        ),
        migrations.RenameModel(
            old_name='Skill',
            new_name='TechSkill',
        ),
    ]
